import { User } from "../users"

export type FleetStatus = "pending" | "suspended" | "active" | "unapproved"

export type Fleet = {
    status: FleetStatus,
    onTransit: boolean,
    suspend: boolean,
    verify: boolean,
    _id: string,
    regNumber: string,
    capacity: string,
    captains?: {
        _id: string,
        isActive: boolean,
        firstName: string,
        lastName: string,
        email: string,
        phoneNumber: string,
    }[],
    image: string,
    model: string,
    registrationNumber: string,
    boatName: string,
    passengerCapacity: string,
    typeOfVessel: string,
    useOfVessel: string,
    constructionMaterial: string,
    HullColor: string,
    superstructureColor: string,
    manufacturer: string,
    manufactureYear: string,
    hullMaterial: string,
    firstAid: boolean,
    lifeJacket: boolean,
    previouslyRegister: boolean,
    validLagosStateOperational: boolean,
    fireExtinguisher: boolean,
    Lifebuoy: boolean,
    VHFTelephone: boolean,
    F4Fenders: boolean,
    GPSCompass: boolean,
    sandBucket: boolean,
    paddle: boolean,
    horn: boolean,
    searchLight: boolean,
    NavigationLight: boolean,
    AddByAdmin: string,
    imgUrl: {
        name: string,
        url: string,
        index: string
    }[],
    User: User,
    createdAt: string,
    updatedAt: string,
}